run:
  timeout: 10m
  allow-parallel-runners: true

linters:
  enable:
    - errname
    - gofmt
    - goimports
    - stylecheck
    - importas
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - mirror
    - staticcheck
    - tagalign
    - testifylint
    - typecheck
    - unused
    - unconvert
    - wastedassign
    - whitespace
    - gocritic
    - exhaustive
    - noctx
    - promlinter

linters-settings:
  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment
